import {chromium, devices} from '../../_tools/node_modules/playwright/index.mjs';
import fs from 'node:fs';
const browser=await chromium.launch({channel:'chrome',headless:true});const results=[];
for(const [name,opts] of [['desktop',{viewport:{width:1440,height:900}}],['iphone',devices['iPhone 13']]]){
 const context=await browser.newContext(opts),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
 await page.goto('http://127.0.0.1:8420/concepts/f-codex/');await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(1000);await page.screenshot({path:`../concepts/f-codex/${name}-hero.png`});
 await page.locator('#teams').scrollIntoViewIfNeeded();await page.waitForTimeout(950);await page.screenshot({path:`../concepts/f-codex/${name}-teams.png`});await page.getByRole('button',{name:'Employee Experience',exact:true}).click();if(!await page.locator('#answer').textContent().then(t=>t.includes('one experience')))throw Error('team switch');
 await page.getByRole('button',{name:'50 visit daily',exact:true}).click();if(await page.locator('#engagements').textContent()!=='18,250'||await page.locator('#unit-cost').textContent()!=='$0.66')throw Error('daily math');await page.getByRole('button',{name:'Source example',exact:true}).click();if(await page.locator('#engagements').textContent()!=='13,550')throw Error('source math');await page.locator('.mixer').scrollIntoViewIfNeeded();await page.waitForTimeout(900);await page.screenshot({path:`../concepts/f-codex/${name}-mixer.png`});
 await page.getByRole('button',{name:'Remote',exact:true}).click();if(await page.locator('#launch-title').textContent()!=='Live demo + signup help')throw Error('launch switch');
 const cdp=await context.newCDPSession(page);await cdp.send('Emulation.setCPUThrottlingRate',{rate:4});await page.evaluate(()=>{scrollTo(0,600);window.framesProbe=[];let last;window.probe=true;function tick(now){if(last)window.framesProbe.push(now-last);last=now;if(window.probe)requestAnimationFrame(tick)}requestAnimationFrame(tick)});
 if(name==='desktop'){for(const dy of [180,140,100,70,40,20,8,-8,-20,-40,-70,-100]){await page.mouse.wheel(0,dy);await page.waitForTimeout(40);}}else{for(const direction of [1,-1,1]){await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:190,y:direction===1?650:260}]});for(let i=1;i<=8;i++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:190,y:(direction===1?650:260)-direction*i*40}]});await page.waitForTimeout(18);}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(350);}}
 await page.waitForTimeout(1000);const before=await page.evaluate(()=>scrollY);await page.waitForTimeout(3000);const delta=await page.evaluate(y=>scrollY-y,before);const frames=await page.evaluate(()=>{window.probe=false;return window.framesProbe});frames.sort((a,b)=>a-b);
 let overflow=0;for(const portion of [0,.2,.4,.6,.8,1]){overflow=Math.max(overflow,await page.evaluate(p=>{scrollTo(0,(document.documentElement.scrollHeight-innerHeight)*p);return document.documentElement.scrollWidth-innerWidth},portion));await page.waitForTimeout(100);}
 await page.emulateMedia({reducedMotion:'reduce'});await page.reload();await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(200);const reduced=await page.evaluate(()=>[...document.querySelectorAll('h1,h2,[data-count]')].every(e=>getComputedStyle(e).opacity==='1'&&e.getBoundingClientRect().height>0)&&[...document.querySelectorAll('.mask>span')].every(e=>getComputedStyle(e).animationName==='none'));
 results.push({viewport:name,consoleErrors:errors,overflow,idleDelta:delta,rafP95:Math.round(frames[Math.floor(frames.length*.95)]*10)/10,rafMax:Math.round(Math.max(...frames)*10)/10,samples:frames.length,reducedMotion:reduced});await context.close();
}
console.log(JSON.stringify(results,null,2));fs.writeFileSync('../concepts/f-codex/verification.json',JSON.stringify(results,null,2));await browser.close();
